#!/usr/bin/env bash
#
# script implements the precommit hook for automatic lint-fix staged files on "git commit"
#
# this script is executed by the pre-commit hook in .git/hooks and will automatically lin-fix all staged files
# any fixes will be automatically be included in the commit
#
# If you want to disable git hooks for some reason you can disable the git hooks by adding `--no-verify` to the git command.
# Example : `git commit --no-verify`
#

# run lint-fix on all staged files and update the staged files with fixes
[[ "$LINTFIX_ON_COMMIT" == 'true' ]] && pnpm lint-fix && git add -u $(git diff --cached --name-only --diff-filter=ACMRT)
