#!/usr/bin/env bash

#
# Generates .vscode/launch.json's xdebug pathMappings from the repo's
# discovered wp-plugin/wp-mu-plugin/wp-theme packages, mapping each to its
# in-container /htdocs/wp-content/... path.
#
# This is intentionally a HOST-side script, not baked into the image/
# entrypoint: VS Code reads launch.json from the host repo, and the mappings
# depend on which plugins/themes/mu-plugins are bind-mounted for a given
# stack - the same discovery scripts/includes/_docker-mounts.sh performs.
#
# Invoked by scripts/start.sh on every `pnpm start`, but also runnable
# standalone.
#
# usage: ./_generate-vscode-launch.sh
#

# bootstrap the environment (provides MNT_HOME, WORDPRESS_VERSION, GIT_ROOT_PATH, ...)
readonly SCRIPTS_HOME="$(realpath "$0" | xargs dirname)/../../../../scripts"
source "${SCRIPTS_HOME}/includes/_bootstrap.sh"
# provides ionos.wordpress.wordpress_version_dir
source "${SCRIPTS_HOME}/includes/_docker-mounts.sh"

cd "$GIT_ROOT_PATH"

readonly VERSION_DIR="$(ionos.wordpress.wordpress_version_dir "$WORDPRESS_VERSION")"
readonly CORE_DIR="${MNT_HOME#./}/wordpress-core/${VERSION_DIR}"
readonly TESTS_DIR="${MNT_HOME#./}/wordpress-tests/trunk"

function plugins {
  for PLUGIN in $(find packages/wp-plugin -mindepth 1 -maxdepth 1 -type d -printf '%f\n' 2>/dev/null || echo ''); do
    echo "        \"/htdocs/wp-content/plugins/${PLUGIN}\": \"\${workspaceFolder}/packages/wp-plugin/${PLUGIN}\","
  done
}

function mu_plugins {
  for PLUGIN in $(find packages/wp-mu-plugin -mindepth 1 -maxdepth 1 -type d -printf '%f\n' 2>/dev/null || echo ''); do
    echo "        \"/htdocs/wp-content/mu-plugins/${PLUGIN}.php\": \"\${workspaceFolder}/packages/wp-mu-plugin/${PLUGIN}/${PLUGIN}.php\","
    if [[ -d "packages/wp-mu-plugin/${PLUGIN}/${PLUGIN}" ]]; then
      echo "        \"/htdocs/wp-content/mu-plugins/${PLUGIN}\": \"\${workspaceFolder}/packages/wp-mu-plugin/${PLUGIN}/${PLUGIN}\","
    fi
  done
}

function themes {
  for THEME in $(find packages/wp-theme -mindepth 1 -maxdepth 1 -type d -printf '%f\n' 2>/dev/null || echo ''); do
    echo "        \"/htdocs/wp-content/themes/${THEME}\": \"\${workspaceFolder}/packages/wp-theme/${THEME}\","
  done
}

mkdir -p .vscode
cat <<EOF > .vscode/launch.json
{
  // THIS FILE IS MACHINE GENERATED by packages/docker/wordpress-alpine/scripts/_generate-vscode-launch.sh - DO NOT EDIT!
  // If you need to configure additional launch configurations consider defining them in a vscode *.code-workspace file
  "version": "0.2.0",
  "configurations": [
    {
      "name": "ionos-wordpress",
      "type": "php",
      "request": "launch",
      "port": 9003,
      "stopOnEntry": false, // set to true for debugging this launch configuration
      "log": false,         // set to true to get extensive xdebug logs
      "pathMappings": {
$(plugins)
$(mu_plugins)
$(themes)
        // phpunit path mappings (\`pnpm test:php\`, mounted by scripts/test.sh)
        "/wordpress-phpunit": "\${workspaceFolder}/${TESTS_DIR}/tests/phpunit",
        "/htdocs/phpunit": "\${workspaceFolder}/phpunit",

        "/htdocs": "\${workspaceFolder}/${CORE_DIR}"
      }
    }
  ]
}
EOF
