version: 2
updates:
  - package-ecosystem: 'npm'
    directories:
      - '/'
      - '/packages/npm/*/*'
      - '/packages/wp-plugin/*/*'
    schedule:
      interval: 'weekly'
    pull-request-strategy: 'single'

  - package-ecosystem: 'docker'
    directories:
      - '/packages/docker/*/*'
    schedule:
      interval: 'weekly'
    pull-request-strategy: 'single'

  - package-ecosystem: 'composer'
    directories:
      - '/packages/docker/**/*'
    schedule:
      interval: 'weekly'
    pull-request-strategy: 'single'

  - package-ecosystem: 'github-actions'
    directories:
      # "For GitHub Actions, use the value /. Dependabot will search the /.github/workflows directory, as well as the action.yml/action.yaml file from the root directory."
      - '/'
    schedule:
      interval: 'weekly'
    pull-request-strategy: 'single'

  - package-ecosystem: 'devcontainers'
    directories:
      - '/.devcontainer'
    schedule:
      interval: 'weekly'
    pull-request-strategy: 'single'
