#
# default stylelint configuration
#
# this file is usually referenced in your own top level .stylelintrc.yaml.
#

extends:
  - stylelint-config-recommended-scss
rules:
  color-named: null
  selector-class-pattern: null
  prettier/prettier: true
  font-family-no-missing-generic-family-keyword:
    ignoreFontFamilies:
      - 'exos-icon-font'
plugins:
  - stylelint-scss
  - stylelint-prettier
