#
# this file will be sourced into "update-dependencies" workspace packages scripts
#

#
# create .vscode/settings.json
#
function ionos.wordpress.vscode.create_settings.json() {
  # generate settings.json
  cat << EOF > '.vscode/settings.json'
// THIS FILE IS MACHINE GENERATED by .wp-env-afterStart.sh - DO NOT EDIT!
// If you need to confgure additional launch configurations consider defining them in a vscode *.code-workspace file
{
  // show workspace folder in editor tab label
  "workbench.editor.labelFormat": "short",
  // see https://github.com/prettier/plugin-php?tab=readme-ov-file#visual-studio-code
  "prettier.documentSelectors": ["**/*.{js,jsx,ts,tsx,json,md,yaml,yml,php}"],
  "prettier.useEditorConfig": true,
  "prettier.configPath": ".prettierrc.js",
  "prettier.ignorePath": ".gitignore",
  "prettier.enableDebugLogs": true,
  "eslint.lintTask.enable": true,
  "eslint.useFlatConfig": true,
  "eslint.format.enable" : true,
  "eslint.ignoreUntitled": true,
  "eslint.run": "onSave",
    "eslint.codeAction.showDocumentation": {
    "enable": true
  },
  "cSpell.useGitignore": true,
  "editorconfig.generateAuto": false,
  "editor.codeActionsOnSave": {
    "source.fixAll": "never",
    "source.fixAll.eslint": "explicit",
    "source.organizeImports": "never"
  },
  "stylelint.validate": ["css", "scss"],
  "stylelint.packageManager": "pnpm",
  "stylelint.config": {
    "configBasedir": "\${workspaceFolder}"
  },
  "stylelint.configFile": ".stylelintrc.yml",
  "[php]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[css]": {
    "editor.defaultFormatter": "stylelint.vscode-stylelint"
  },
  "[scss]": {
    "editor.defaultFormatter": "stylelint.vscode-stylelint"
  },
  "eslint.validate": ["javascript", "javascriptreact", "json", "jsonc", "json5"],
  // enable globally (here: format on save)
  "editor.formatOnSave": false,
  "intelephense.files.exclude": [
    "**/.git/**",
    "**/.svn/**",
    "**/.hg/**",
    "**/CVS/**",
    "**/.DS_Store/**",
    "**/node_modules/**",
    "**/bower_components/**",
    "**/vendor/**/{Tests,tests}/**",
    "**/.history/**",
    "**/vendor/**/vendor/**",
    "**/dist/**",
    "**/build/**",
  ],
  "search.useIgnoreFiles": true,
  "search.exclude": {
    // Avoid polluting search results with lockfile content
    "pnpm-lock.yaml": true,
    "**/build/**": true,
    "**/dist/**": true,
    "**/node_modules/**": true,
    "**/vendor/**": true,
    "**/*.sbom.syft.json": true,
  },
  // Ensure VSCode uses pnpm instead of npm
  "npm.packageManager": "pnpm",

  "intelephense.environment.phpVersion": "8.3",
  "intelephense.environment.includePaths": [
    "${WPENV_INSTALLPATH:-}/WordPress",
    "./phpunit/vendor/phpunit/phpunit/src"
  ],
  "git.autoRepositoryDetection": false,
  "json.schemas": [
    {
      "fileMatch": ["jsonschema.json", "*schema.json"],
      "url": "https://json-schema.org/draft/2019-09/schema"
    },
    {
      "fileMatch": ["tsconfig.json"],
      "url": "https://json.schemastore.org/tsconfig"
    }
  ],
  "[html]": {
    "editor.formatOnSave": false
  },
  "playwright.runGlobalSetupOnEachRun": true,
  "files.trimTrailingWhitespace": false,
  "files.trimTrailingWhitespaceInRegexAndStrings": false
  "github.copilot.chat.commitInstructions" : [
    "Always follow the commit message format defined in the project's docs/agent/git-conventions.md file.",
    "Use the specific prefixes and header styles found in that document."  
  ],
  "geminicodeassist.enableTelemetry": false,
  "geminicodeassist.contextFiles": ["AGENTS.md"]
}
EOF
}

export -f ionos.wordpress.vscode.create_settings.json
