name: 'devcontainer image name'
description: |
  set up environment variable IMAGE_NAME containing the computed dev container image.
  the dev container image name is constructed from the repository owner/name and the branch name all lowercased.
  example : ghcr.io/IONOS-Wordpress/ionos-wordpress-develop-devcontainer for develop branch
# inputs:
#   who-to-greet:  # id of input
#     description: 'Who to greet'
#     required: true
#     default: 'World'
outputs:
  image_name:
    description: 'the computed image name'
    value: ${{ steps.compute_image_name.outputs.image_name }}

runs:
  using: 'composite'
  steps:
    - id: compute_image_name
      shell: bash
      run: |
        LAST_MODIFIED=$(git log -1 --format="%cd" --date=format:'%Y-%m-%d-%H-%M-%S' -- .devcontainer)
        # construct image_name from repo owner/name and branch
        # example value : "ghcr.io/IONOS-Wordpress/ionos-wordpress-2025-12-24-14-48-33-devcontainer"
        image_name="ghcr.io/${GITHUB_REPOSITORY}-${LAST_MODIFIED}-devcontainer"
        # convert image_name to lowercase and provide it as step variable "image_name"
        echo "image_name=${image_name@L}" >> "$GITHUB_OUTPUT"
