#!/usr/bin/env bash

#
# script is not intended to be executed directly. use `pnpm exec ...` instead or call it as package script.
#
# this script cleans up the environment as if it was never started
#
# ATTENTION: Please ensure that the dev container is stopped before cleaning up
#

# bootstrap the environment
source "$(realpath $0 | xargs dirname)/includes/_bootstrap.sh"

# MARK: test dev container not running
# ensure the dev container is not running before cleaning up
if ionos.wordpress.container_running "$CONTAINER_NAME"; then
  ionos.wordpress.log_warn "dev container '$CONTAINER_NAME' is already running. Excecute 'pnpm stop' or 'pnpm destroy' to stop it before cleaning up."
  exit 1
fi
# ENDMARK

# MARK: cleanup docker images
# loop over all docker workspace packages
for PACKAGE_JSON in $(find packages/docker -maxdepth 2 -mindepth 2 -name "package.json" 2>/dev/null ||:); do
# we need to encase the loop in a subshell to avoid variable pollution
(
  # inject .env and .secret files from plugin directory
  ionos.wordpress.load_env "$(dirname "$PACKAGE_JSON")"

  PACKAGE_NAME=$(jq -r '.name' "$PACKAGE_JSON")
  PACKAGE_VERSION=$(jq -r '.version' "$PACKAGE_JSON")
  DOCKER_IMAGE_NAME="$(ionos.wordpress.docker_image_name_for_package "$PACKAGE_NAME")"

  ionos.wordpress.log_warn "remove local docker image $DOCKER_IMAGE_NAME:$PACKAGE_VERSION if exists"

  # remove all docker containers using the image
  docker ps -a -q --filter ancestor=$DOCKER_IMAGE_NAME:$PACKAGE_VERSION | xargs -r docker rm -f
  # delete docker image
  docker image rm -f $DOCKER_IMAGE_NAME:$PACKAGE_VERSION 2>/dev/null ||:
)
done
# remove docker images generated by workspace packages

# ENDMARK:

git clean $GIT_CLEAN_OPTS \
  -ff \
  -e '!/*.code-workspace' \
  -e '!/*.secrets' \
  -e '!/*.env.local'

