#!/usr/bin/env bash

#
# script is not intended to be executed directly. use `pnpm exec ...` instead or call it as package script.
#
# this script is used to lint the codebase
#

# bootstrap the environment
source "$(realpath $0 | xargs dirname)/includes/_bootstrap.sh"

FIX=no
POSITIONAL_ARGS=()

USE=()

while [[ $# -gt 0 ]]; do
  case $1 in
    --help)
      ionos.wordpress.print_help "$0"
      ;;
    --fix)
      FIX=yes
      shift
      ;;
    --use)
      ionos.wordpress.parse_use_flag "$2"
      shift 2
      ;;
    -*|--*)
      echo "Unknown option $1"
      exit 1
      ;;
    *)
      POSITIONAL_ARGS+=("$1")
      shift # past argument
      ;;
  esac
done

[[ ${#POSITIONAL_ARGS[@]} -eq 0 ]] && POSITIONAL_ARGS=(".")

# invoke all linters by default
ionos.wordpress.default_use_to_all

function ionos.wordpress.prettier() {
  ionos.wordpress.log_header "$([[ "$FIX" == 'yes' ]] && echo -n "lint-fix" || echo -n "lint") html/yml/md/etc. files with prettier ..."

  # prettier
  pnpm exec prettier --config ./.prettierrc.js --ignore-path ./.prettierignore --ignore-path ./.gitignore --ignore-path ./.lintignore --check --ignore-unknown --log-level log \
    $([[ "$FIX" == 'yes' ]] && echo -n "--write" ||:) \
    ${POSITIONAL_ARGS[@]}
}

function ionos.wordpress.eslint() {
  ionos.wordpress.log_header "$([[ "$FIX" == 'yes' ]] && echo -n "lint-fix" || echo -n "lint") js/jsx files with eslint ..."

  # eslint
  pnpm exec eslint --config ./eslint.config.mjs --no-error-on-unmatched-pattern --no-warn-ignored \
    $([[ "$FIX" == 'yes' ]] && echo -n "--fix" ||:) \
    ${POSITIONAL_ARGS[@]}
}

function ionos.wordpress.stylelint() {
  ionos.wordpress.log_header "$([[ "$FIX" == 'yes' ]] && echo -n "lint-fix" || echo -n "lint") css/scss files with stylelint ..."

  [[ "${POSITIONAL_ARGS[@]}" == '.' ]] && POSITIONAL_ARGS=('**/*.{css,scss}')

  # stylelint
  pnpm exec stylelint \
    --config ./.stylelintrc.yml \
    --ignore-path ./.gitignore \
    --ignore-path ./.lintignore \
    --ignore-pattern '**/*.*' \
    --ignore-pattern '!**/*.css' \
    --ignore-pattern '!**/*.scss' \
    --allow-empty-input \
    --formatter=compact \
    --no-cache \
    $([[ "$FIX" == 'yes' ]] && echo -n '--fix strict' ||:) \
    ${POSITIONAL_ARGS[@]}
}

function ionos.wordpress.ecs() {
  ionos.wordpress.log_header "$([[ "$FIX" == 'yes' ]] && echo -n "lint-fix" || echo -n "lint") php files files with ecs ..."

  # go interactively into the docker image :
  # docker run -q --rm -ti --user 1000:1000 -v $(pwd):/project/ --entrypoint /bin/sh ionos-wordpress/ecs-php
  # command : /composer/vendor/bin/ecs check --no-diffs --clear-cache --config ./packages/docker/ecs-php/ecs-config.php --no-progress-bar .

  # the docker image bind-mounts the workspace at /project and its WORKDIR is /project, so
  # every path below is already relative to the repository root - which is also the working
  # directory the native ecs runs in. that is why the argument list is shared verbatim
  # between both modes instead of being translated.
  local args=(
    check
    $([[ "$FIX" == 'yes' ]] && echo -n "--fix" ||:)
    --no-diffs --clear-cache --config ./packages/docker/ecs-php/ecs-config.php --no-progress-bar --memory-limit=1G
    ${POSITIONAL_ARGS[@]}
  )

  # ecs-config.php resolves the wpcs standards through $COMPOSER_HOME (native mode only -
  # harmless no-op in docker mode, the image already has its own COMPOSER_HOME baked in)
  local ecs_docker_flags=(--user "$DOCKER_USER")
  COMPOSER_HOME="$(ionos.wordpress.native_tool_composer_home ecs-php)" \
    ionos.wordpress.run_native_or_docker ecs-php ionos-wordpress/ecs-php ecs_docker_flags "${args[@]}"
}

# kept for reference - not used anymore
# # checks wordpress coding standards using phpcs
# # @FIXME: actually this could be done also using ecs but as of now it's not implemented
# function ionos.wordpress.phpcs() {
#   ionos.wordpress.log_header "$([[ "$FIX" == 'yes' ]] && echo -n "lint-fix" || echo -n "lint") php files with PHP Codefixer ..."

#   # php-cs
#   cat <<EOF | docker run \
#     $DOCKER_FLAGS \
#     --rm \
#     -i \
#     --user "$DOCKER_USER" \
#     -v $(pwd):/project/ \
#     -v $(pwd)/ecs-config.php:/ecs-config.php \
#     -v $(pwd)/packages/docker/ecs-php/ruleset.xml:/ruleset.xml \
#     --entrypoint /bin/sh \
#     ionos-wordpress/ecs-php \
#     -
#       echo "Running $([[ "$FIX" == 'yes' ]] && echo -n "phpcs" || echo -n "phpcs" ) ..."
#       $([[ "$FIX" == 'yes' ]] && echo -n "phpcs" || echo -n "phpcs" ) \
#       -s --no-cache --standard=/ruleset.xml \
#       ${POSITIONAL_ARGS[@]}
# EOF
# # @FIXME: right now we only use phpcs
# # echo "Running $([[ "$FIX" == 'yes' ]] && echo -n "phpcbf" || echo -n "phpcs" ) ..."
# # $([[ "$FIX" == 'yes' ]] && echo -n "phpcbf" || echo -n "phpcs" ) \
#   if [[ $? -ne 0 ]]; then
#     return 1
#   fi
# }

#
# adds a line stating that the msgid was generated by deepl
# before each line starting with 'msgid' in the given PO file
# if the line was changed
#
# $1 the path to the PO file
#
function ionos.wordpress.mark_added_deepl_translations() {
  local PO_FILE="$1"
  local lines=()

  local readonly GENERATED_BY_DEEPL_COMMENT="#, generated by deepl"

  readarray -t lines < "$PO_FILE"

  # Loop over each line in the array
  for (( i=0; i<${#lines[@]}; i++ )); do
    # if you found a line containing only 'msgstr ""'
    if [[ "${lines[i]}" == 'msgstr ""' ]]; then

      # continue if the previous line is the generated comment
      if [[ $i -lt 2 ]] || [[ "${lines[i-2]}" == "$GENERATED_BY_DEEPL_COMMENT"* ]]; then
        continue
      fi

      # Add the generated by deepl comment before the current line
      lines[i-1]=$(echo -e "$GENERATED_BY_DEEPL_COMMENT\n${lines[i-1]}")
    fi
  done

  # Write the modified lines back to the file
  printf "%s\n" "${lines[@]}" > "$PO_FILE"
}

# checks wordpress plugin translations using dennis (https://github.com/mozilla/dennis)
function ionos.wordpress.dennis() {
  if [[ "$FIX" == 'yes' ]] && [[ "${USE[@]}" =~ i18n ]]; then
    # abort lint fix if DEEP_API_KEY is not set
    if [[ -z "${DEEPL_API_KEY}" ]]; then
      ionos.wordpress.log_warn "Skip auto translating po files using deepl - DEEPL_API_KEY environment variable is not set in './.secrets'"
      exit 0
    fi

    ionos.wordpress.log_header "auto translating po files with missing translations using deepl ..."

    # loop over all po files and translate missing entries
    for PO_FILE in $(find ./packages -maxdepth 5 -mindepth 4 -type f -path '*/languages/*.po'); do
      # extract target language from file name
      TARGET_LANGUAGE=$(basename "$PO_FILE" | sed -n 's/.*-\([a-zA-Z_]*\)\.po$/\1/p')

      # deepl requires simple language names like "de" instead of "de_DE"
      # except for english - there we need to replace "_" with "-" to get en_US | en-GB
      if [[ "$TARGET_LANGUAGE" == en* ]]; then
        # en_US with en-US
        TARGET_LANGUAGE="${TARGET_LANGUAGE//_/-}"
      else
        # strip country code from language for all other languages
        TARGET_LANGUAGE="${TARGET_LANGUAGE%%_*}"
      fi

      ionos.wordpress.mark_added_deepl_translations "$PO_FILE"

      echo "auto translate missing entries in $PO_FILE to language $TARGET_LANGUAGE"

      # paths are relative to the repository root in both modes - see ionos.wordpress.ecs
      potrans_args=(
        deepl
        --from="en"
        --to="$TARGET_LANGUAGE"
        --no-cache
        --translator=packages/docker/potrans/class-xmlsafedeepltranslator.php
        $PO_FILE
        $(dirname $PO_FILE)
      )

      # translate missing entries
      potrans_docker_flags=(-i -e DEEPL_API_KEY="${DEEPL_API_KEY}")
      DEEPL_API_KEY="${DEEPL_API_KEY}" \
        ionos.wordpress.run_native_or_docker potrans ionos-wordpress/potrans potrans_docker_flags "${potrans_args[@]}" || (
        ionos.wordpress.log_error "auto translation failed - see error above"
        exit 1
      )

      # potrans wil regenerate the po file even if no localization changes are
      # present in source files with a new creation date so that git always
      # solution:
      #   revert generated pot file to git version if nothing but po headers changed
      diff_error_code=0
      # strip creation date and generator lines and line numbers using sed
      cmp -s \
        <(sed -e '/^".*$/d' -e 's/^\(#:.*\):[0-9]\+/\1/g' $PO_FILE) \
        <(git show HEAD:$PO_FILE 2>/dev/null | sed -e '/^".*$/d' -e 's/^\(#:.*\):[0-9]\+/\1/g') \
        || diff_error_code=$?

      [[ "0" == "$diff_error_code" ]] && git checkout $PO_FILE
    done

    exit 0
  fi

  ionos.wordpress.log_header "lint po/pot files with dennis ..."

  # [[ "${POSITIONAL_ARGS[@]}" == '.' ]] && POSITIONAL_ARGS=($(find packages/wp-plugin -maxdepth 2 -mindepth 2 -type d  -name "languages"))
  POSITIONAL_ARGS=($(find packages/wp-plugin -maxdepth 2 -mindepth 2 -type d  -name "languages"))

  # paths are relative to the repository root in both modes - see ionos.wordpress.ecs
  dennis_args=(status --showuntranslated ${POSITIONAL_ARGS[@]})

  # dennis
  dennis_docker_flags=(-i)
  OUTPUT=$(ionos.wordpress.run_native_or_docker dennis-i18n ionos-wordpress/dennis-i18n dennis_docker_flags "${dennis_args[@]}")

  # map file path references from within docker container to host paths
  # and filter out unwanted lines (everything except untranslated string messages).
  # the '/project/' rewrite below is a no-op in native mode - dennis then already reports
  # the relative paths it was given.
  echo "$OUTPUT" | \
    grep -vE '^\s|^Metadata|Statistics|Untranslated\sstrings' | \
    grep -vE '^[0-9]+:#' | \
    grep -vE '^[0-9]+:msgstr ""' | \
    grep -v '^$' | \
    sed 's|Working on: /project/|Working on: ./|ig'

  # abort with error if there were untranslated strings
  if echo "$OUTPUT" | grep -q 'Untranslated:\s*[1-9]'; then
    ionos.wordpress.log_error "dennis validation failed : some strings are untranslated"
    return 1
  fi
}

#
# check if pnpm lock file (`./pnpm-lock.yaml`) is up to date
# and references all workspace dependencies correctly.
# also asserts the pnpm version pin in package.json matches the devcontainer image
#
function ionos.wordpress.pnpm() {
  if [[ "$FIX" == 'yes' ]]; then
    pnpm install
  fi

  ionos.wordpress.log_header "lint pnpm version pin ..."

  # package.json's `packageManager` is authoritative at runtime : pnpm silently switches itself to
  # that version, which would make the devcontainer's ENV PNPM_VERSION cosmetic if the two drift.
  # the Dockerfile needs its own literal since it installs pnpm before the repo is copied in.
  PACKAGE_JSON_PNPM_VERSION=$(pnpm exec node -p "(require('./package.json').packageManager ?? '').replace(/^pnpm@/, '')")
  DOCKERFILE_PNPM_VERSION=$(grep -oP '^ENV PNPM_VERSION \K.+' ./.devcontainer/Dockerfile)

  if [[ -z "$PACKAGE_JSON_PNPM_VERSION" ]]; then
    # the filename:line notation is required for vscode tasks to jump to the correct file
    ionos.wordpress.log_error "package.json:1 : no pnpm version pinned - expected '\"packageManager\": \"pnpm@$DOCKERFILE_PNPM_VERSION\"'"
    return 1
  fi

  if [[ "$PACKAGE_JSON_PNPM_VERSION" != "$DOCKERFILE_PNPM_VERSION" ]]; then
    ionos.wordpress.log_error "package.json:1 : pinned pnpm version 'pnpm@$PACKAGE_JSON_PNPM_VERSION' does not match .devcontainer/Dockerfile 'ENV PNPM_VERSION $DOCKERFILE_PNPM_VERSION'"
    return 1
  fi

  ionos.wordpress.log_header "lint pnpm lock file ..."

  if [[ ! -f ./pnpm-lock.yaml ]]; then
    # the filename:line notation is required for vscode tasks to jump to the correct file
    ionos.wordpress.log_error "pnpm-lock.yaml:1 : pnpm-lock.yaml not found"
    return 1
  fi

  # backup lock file
  PNPM_LOCK_YAML=$(cat ./pnpm-lock.yaml)

  # validate lock file is valid
  if ! pnpm -s install --lockfile-only; then
    # the filename:line notation is required for vscode tasks to jump to the correct file
    ionos.wordpress.log_error "pnpm-lock.yaml:1 : pnpm-lock.yaml outdated - please update it using 'pnpm install'"
    return 1
  fi

  # restore lock file
  echo "$PNPM_LOCK_YAML" > ./pnpm-lock.yaml
}

#
# path of the file that repeats the version pins - see ionos.wordpress.version_pins()
IONOS_VERSION_PIN_MIRROR='.devcontainer/Dockerfile'

#
# asserts that one version pin has the same value in its own file and in
# $IONOS_VERSION_PIN_MIRROR. echoes what is wrong and returns 1 on mismatch.
#
# @param $1 what is pinned (used in the error message, e.g. "composer")
# @param $2 file holding the authoritative pin
# @param $3 grep -P pattern capturing the version in $2 via \K
# @param $4 grep -P pattern capturing the version in $IONOS_VERSION_PIN_MIRROR via \K
#
function ionos.wordpress.assert_version_pin() {
  local what="$1" file="$2" regex="$3" mirror_regex="$4"
  local mirror="$IONOS_VERSION_PIN_MIRROR"
  local result=0

  # "<line>:<version>" of the first match, empty if the pattern does not match (any more)
  local match="$(grep -noP "$regex" "$file" | head -1 ||:)"
  local mirror_match="$(grep -noP "$mirror_regex" "$mirror" | head -1 ||:)"

  # a pattern that stopped matching must fail loudly - a check that passes because it no
  # longer finds anything is worse than no check at all
  local unmatched
  for unmatched in "$file|$regex|$match" "$mirror|$mirror_regex|$mirror_match"; do
    IFS='|' read -r pin_file pin_regex pin_match <<<"$unmatched"
    if [[ -z "$pin_match" ]]; then
      # single argument on purpose - log_error's $2 is a stacktrace index, not more message.
      # the filename:line notation is required for vscode tasks to jump to the correct file
      local message="$pin_file:1 : cannot find the $what version pin ('$pin_regex' matches"
      message+=" nothing) - update the ionos.wordpress.assert_version_pin call sites below"
      ionos.wordpress.log_error "$message"
      result=1
    fi
  done
  [[ $result -eq 0 ]] || return 1

  if [[ "${match#*:}" != "${mirror_match#*:}" ]]; then
    # single argument on purpose - log_error's $2 is a stacktrace index, not more message.
    # the filename:line notation is required for vscode tasks to jump to the correct file
    local message="$mirror:${mirror_match%%:*} : pinned $what version '${mirror_match#*:}'"
    message+=" does not match $file:${match%%:*} '${match#*:}' - bump both together"
    ionos.wordpress.log_error "$message"
    return 1
  fi
}

#
# assert that the version pins which necessarily exist twice still agree.
#
# $IONOS_VERSION_PIN_MIRROR has to repeat several pins as literals: it is built by the
# devcontainer CLI / vscode / devcontainers/ci, none of which source the repo's .env files or
# scripts/includes/*, and devcontainer.json's build.args can only interpolate ${localEnv:...}
# (the developer's shell, not a file in the repo). so no shared variable can reach it - the
# duplication is unavoidable and only the agreement can be enforced. see .beans/47l4--*.md.
#
# without this the failure mode is silent: bump one half, forget the other, and both paths
# keep working - they just stop being the same tool. not hypothetical: the composer pin was
# already drifting (the dev container base image ships composer 2.10.3, the pinned fallback
# image 2.10.2) when .beans/b5q8--*.md made composer a native tool.
#
# ionos.wordpress.pnpm() checks the pnpm pin, which has the same shape but reads its value
# from package.json via node rather than by pattern - left where it is on purpose.
#
function ionos.wordpress.version_pins() {
  if [[ "$FIX" == 'yes' ]]; then
    # nothing to fix automatically - a pin bump changes which tool version everybody runs
    # and is a decision, not a formatting detail
    :
  fi

  ionos.wordpress.log_header "lint duplicated version pins ..."

  local result=0

  # the native composer and the dockerized fallback must be the identical binary
  ionos.wordpress.assert_version_pin composer \
    scripts/includes/_native-tools.sh "IONOS_COMPOSER_DOCKER_IMAGE='composer:\K[^']+" \
    '^COPY --from=composer:\K\S+' || result=1

  ionos.wordpress.assert_version_pin dennis \
    packages/docker/dennis-i18n/.env '^DENNIS_VERSION=\K.+' \
    '^ARG DENNIS_VERSION=\K.+' || result=1

  # the three PHP tools must run on the same interpreter version natively as in their images
  # (.beans/e6mc--*.md, decision 3)
  local tool
  for tool in ecs-php rector-php potrans; do
    ionos.wordpress.assert_version_pin php \
      "packages/docker/$tool/.env" '^PHP_VERSION=\K.+' \
      '^FROM mcr\.microsoft\.com/devcontainers/php:\K[^-]+' || result=1
  done

  return $result
}

#
# check if plugin files have all headers
#
function ionos.wordpress.wordpress_plugin() {
  if [[ "$FIX" == 'yes' ]]; then
    # there is nothing done yet in lint-fix mode
    :
  fi

  ionos.wordpress.log_header "lint wordpress plugin header files ..."

  exit_code=0

  # loop over all plugin directories
  for dir in $(find ./packages/{wp-plugin,wp-mu-plugin} -maxdepth 1 -mindepth 1 -type d); do
    for plugin_file in $(ionos.wordpress.get_plugin_filenames $dir); do
      echo "checking $dir/$plugin_file"

      # test version is same as in package.json
      PLUGIN_VERSION=$(grep -oP "Version:\s*\K[0-9.]*" $dir/$plugin_file)
      PACKAGE_VERSION=$(jq -r '.version' $dir/package.json)
      if [[ "$PLUGIN_VERSION" != "$PACKAGE_VERSION" ]]; then
        ionos.wordpress.log_error "$dir/$plugin_file:1 : plugin version(=$PLUGIN_VERSION) does not match package.json version(=$PACKAGE_VERSION)"
        exit_code=1
      fi

      # test 'Description' field
      if ! grep -qoP "Description:\s*.+$" $dir/$plugin_file; then
        ionos.wordpress.log_error "$dir/$plugin_file:1 : plugin header 'Description' is missing or empty"
        exit_code=1
      fi

      # test 'Requires at least' field
      if ! grep -qoP "Requires at least:\s*.+$" $dir/$plugin_file; then
        ionos.wordpress.log_error "$dir/$plugin_file:1 : plugin header 'Requires at least' is missing or empty"
        exit_code=1
      fi

      # test 'Plugin URI' field
      if ! grep -qoP "Plugin URI:\s*.+$" $dir/$plugin_file; then
        ionos.wordpress.log_error "$dir/$plugin_file:1 : plugin header 'Plugin URI' is missing or empty"
        exit_code=1
      fi


      # test 'Author' field
      if ! grep -qoP "Author:\s*.+$" $dir/$plugin_file; then
        ionos.wordpress.log_error "$dir/$plugin_file:1 : plugin header 'Author' is missing or empty"
        exit_code=1
      fi

      # test 'Author URI' field
      if ! grep -qoP "Author URI:\s*.+$" $dir/$plugin_file; then
        ionos.wordpress.log_error "$dir/$plugin_file:1 : plugin header 'Author URI' is missing or empty"
        exit_code=1
      fi

      # test 'Domain Path' field
      if ! grep -qoP "Domain Path:\s*/.+$" $dir/$plugin_file; then
        ionos.wordpress.log_error "$dir/$plugin_file:1 : plugin header 'Domain Path: <languages-dir-path>' is missing or invalid"
        exit_code=1
      fi

      # following checks are only for plugins in wp-plugin (not mu-plugins)
      if [[ "$(dirname $dir)" == './packages/wp-mu-plugin' ]]; then
        continue
      fi
      # test 'Update URI' field
      if (! grep -qoP "Update URI:\s*.+$" $dir/$plugin_file); then
        ionos.wordpress.log_error "$dir/$plugin_file:1 : plugin header 'Update URI' is missing or empty"
        exit_code=1
      fi
    done
  done

  return $exit_code
}

# ensure required docker images are built - but only those the selected linters
# actually use. building all of them unconditionally was wasted work (and in CI
# forced a pull/push of images that are never invoked).
# note: potrans is only used by the deepl auto-translation in 'lint-fix --use i18n'
#
# a tool that is available natively (dev container, CI) needs no image at all, so it is
# left out of the filters entirely - that is what removes the "first lint builds docker
# images" wait from a fresh dev container. see scripts/includes/_native-tools.sh
# "tool:use-pattern:requires-fix" rows driving the guard below - add a new
# linter/tool by adding one row here instead of a hand-copied if block.
DOCKER_BUILD_FILTER_TOOLS=(
  'ecs-php:all|php:'
  'dennis-i18n:all|i18n:'
  'potrans:i18n:yes'
)

DOCKER_BUILD_FILTERS=()
for entry in "${DOCKER_BUILD_FILTER_TOOLS[@]}"; do
  IFS=':' read -r tool use_pattern requires_fix <<<"$entry"
  if [[ -z "$requires_fix" || "$FIX" == 'yes' ]] &&
    [[ "${USE[@]}" =~ $use_pattern ]] &&
    ionos.wordpress.needs_docker_tools "$tool"; then
    DOCKER_BUILD_FILTERS+=(--filter "$tool")
  fi
done
if [[ ${#DOCKER_BUILD_FILTERS[@]} -gt 0 ]]; then
  pnpm build "${DOCKER_BUILD_FILTERS[@]}" > /dev/null
fi

declare -A summaries=()

set +e
if [[ "${USE[@]}" =~ all|php|wp ]]; then
  if ionos.wordpress.wordpress_plugin; then
    summaries["wp"]="WordPress $( [[ "$FIX" == 'yes' ]] && echo 'lint fixing' ||  echo 'linting') was successful."
  else
    exit_code=1
    summaries["wp"]="WordPress $( [[ "$FIX" == 'yes' ]] && echo 'lint fixing' ||  echo 'linting') reported errors."
  fi
fi

# if [[ "${USE[@]}" =~ all|php ]]; then
#   ionos.wordpress.phpcs || exit_code=1
# fi

if [[ "${USE[@]}" =~ all|php ]]; then
 if ionos.wordpress.ecs; then
    summaries["php"]="PHP $( [[ "$FIX" == 'yes' ]] && echo 'lint fixing' ||  echo 'linting') was successful."
  else
    exit_code=1
    summaries["php"]="PHP $( [[ "$FIX" == 'yes' ]] && echo 'lint fixing' ||  echo 'linting') reported errors."
  fi
fi

if [[ "${USE[@]}" =~ all|prettier ]]; then
  if ionos.wordpress.prettier; then
    summaries["prettier"]="Prettier $( [[ "$FIX" == 'yes' ]] && echo 'lint fixing' ||  echo 'linting') was successful."
  else
    exit_code=1
    summaries["prettier"]="Prettier $( [[ "$FIX" == 'yes' ]] && echo 'lint fixing' ||  echo 'linting') reported errors."
  fi
fi

if [[ "${USE[@]}" =~ all|js ]]; then
  if ionos.wordpress.eslint; then
    summaries["js"]="Javascript $( [[ "$FIX" == 'yes' ]] && echo 'lint fixing' ||  echo 'linting') was successful."
  else
    exit_code=1
    summaries["js"]="Javascript $( [[ "$FIX" == 'yes' ]] && echo 'lint fixing' ||  echo 'linting') reported errors."
  fi
fi

if [[ "${USE[@]}" =~ all|css ]]; then
  if ionos.wordpress.stylelint; then
    summaries["css"]="CSS $( [[ "$FIX" == 'yes' ]] && echo 'lint fixing' ||  echo 'linting') was successful."
  else
    exit_code=1
    summaries["css"]="CSS $( [[ "$FIX" == 'yes' ]] && echo 'lint fixing' ||  echo 'linting') reported errors."
  fi
fi

if [[ "${USE[@]}" =~ all|pnpm ]]; then
  if ionos.wordpress.pnpm; then
    summaries["pnpm"]="PNPM $( [[ "$FIX" == 'yes' ]] && echo 'lint fixing' ||  echo 'linting') was successful."
  else
    exit_code=1
    summaries["pnpm"]="PNPM $( [[ "$FIX" == 'yes' ]] && echo 'lint fixing' ||  echo 'linting') reported errors."
  fi
fi

if [[ "${USE[@]}" =~ all|pins ]]; then
  if ionos.wordpress.version_pins; then
    summaries["pins"]="Duplicated version pins are consistent."
  else
    exit_code=1
    summaries["pins"]="Duplicated version pins reported errors."
  fi
fi

if [[ "${USE[@]}" =~ all|i18n ]]; then
  if ionos.wordpress.dennis; then
    summaries["i18n"]="i18n $( [[ "$FIX" == 'yes' ]] && echo 'lint fixing' ||  echo 'linting') was successful."
  else
    exit_code=1
    summaries["i18n"]="i18n $( [[ "$FIX" == 'yes' ]] && echo 'lint fixing' ||  echo 'linting') reported errors."
  fi
fi

echo ''

error_count=0
for key in "${!summaries[@]}"; do
  message="${summaries[$key]}"

  if [[ "$message" =~ errors ]]; then
    error_count=$(( $error_count + 1 ))
    echo -e "\e[31m$message\e[0m"
  else
    echo "$message"
  fi
done

echo ''

if [[ $error_count -gt 0 ]]; then
  echo -e "\e[31m$error_count linter(s) reported errors.\e[0m"
else
  echo "Linting passed successfully."
fi

exit ${exit_code:-0}

###help-message
Syntax: 'pnpm run lint [options] [additional-args]'

By default every source file will be linted.

Options:

  --help    Show this help message and exit

  --fix     Apply lint fixes where possible

  --use     Specify which linters to use (default: all)

            Available options:
              - all      operate on all files
              - php      operate on php files
              - prettier operate html/yml/md/etc. files
              - wp       operate on wordpress plugin/theme entry files
              - js       operate on js/jsx files
              - css      operate on css/scss files
              - pnpm     operate on pnpm lock file
              - i18n     operate on po/pot files
              - pins     check the version pins duplicated in .devcontainer/Dockerfile

              The i18n allows automatic translation of po files using deepl.com if 'DEEPL_API_KEY' is set in './.secrets'
              See './.secret.example' for an example file.

  Usage:
    Lint all files matching all linters
    'pnpm run lint'

    Lint fix all files (except i18n)
    'pnpm run lint-fix'

    Lint fix i18n files
    'pnpm run lint-fix:i18n'

    lint fix will auto translate untranslated messages in po files using deepl.com if 'DEEPL_API_KEY' is set in './.secrets'
    the touched po files will be marked with a comment stating that the translation was generated by deepl

    Lint all files matching prettier and i18n, skip php files etc.
    'pnpm run lint --use prettier --use i18n'

    Lint fix all files matching php and i18n
    'pnpm run lint-fix --use prettier --use i18n' or
    'pnpm run lint -fix --use prettier --use i18n'

see ./docs/4-lint.md for more informations
