#
# this is the prerelease workflow that is triggered by a push to the main branch
# it will create a new github release including tags and marks that release as pre-release
#
# this workflow requires a secret "GCHAT_RELEASE_ANNOUNCEMENTS_WEBHOOK" to point to the google chat room
# if not declared his workflow will set a warning and will exit gracefully (=> without an error)
#
# it will
# - update the versions of all packages
# - build the project
# - @TODO test the project
# - create a release for all packages that have changed and add its artifacts to the release
# - gather the workflow artifacts
#
name: 'pre-release'

# execute this workflow only on the main branch and wait until the integration workflow is completed
on:
  push:
    branches:
      - main

permissions:
  # write-all is too much, but we need to write to packages
  # see https://github.com/orgs/community/discussions/57724 for more info
  contents: write
  packages: write
  attestations: write
  id-token: write

jobs:
  devcontainer:
    uses: ./.github/workflows/build-devcontainer-image.yaml
    secrets: inherit

  # integration:
  #   uses: ./.github/workflows/integration.yaml
  #   secrets: inherit

  pre-release:
    runs-on: ubuntu-latest
    needs:
      - devcontainer
      # - integration
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    if: "!contains(github.event.head_commit.message, 'skip release')"
    steps:
      - name: checkout branch from git
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: './.github/shared/actions/devcontainer-shell-run'
        name: build_project
        with:
          runCmd: |
            export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
            export GCHAT_RELEASE_ANNOUNCEMENTS_WEBHOOK="${{ secrets.GCHAT_RELEASE_ANNOUNCEMENTS_WEBHOOK }}"

            pnpm install --frozen-lockfile
            pnpm pre-release

      - uses: './.github/shared/actions/devcontainer-shell-run'
        id: gather_workflow_artifacts
        name: gather_workflow_artifacts
        with:
          runCmd: |
            pnpm exec ./scripts/_get-workflow-artefacts.sh

      - name: attach workflow artifacts
        uses: actions/upload-artifact@v4
        with:
          # see https://github.com/actions/upload-artifact/issues/424
          path: |-
            ${{ steps.gather_workflow_artifacts.outputs.runCmdOutput }}
          # overwrite: true
