#
# this workflow will move the release flagged as 'pre-release' to the release named 'latest'
#
# see ./scripts/release.sh for details
#
name: 'release (manual workflow)'

on:
  # this workflow needs to be triggered manually
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    # ensure only one pipeline is running this workflow at a time
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      # only run on main branch
      - name: Check branch
        if: github.ref_name != 'main'
        run: |
          echo "::error::Workflow can only be run on branch 'main'"
          exit 1

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: '${{ github.ref_name }}'

      - name: release
        run: |
          export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          export GCHAT_RELEASE_ANNOUNCEMENTS_WEBHOOK="${{ secrets.GCHAT_RELEASE_ANNOUNCEMENTS_WEBHOOK }}"
          export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
          export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"

          # by calling this script directly in the pipeline we dont need to install pnpm :-)
          # pnpm release
          ./scripts/release.sh
