#!/usr/bin/env bash

#
# Generates .vscode/launch.json's xdebug pathMappings from the repo's
# discovered wp-plugin/wp-mu-plugin/wp-theme packages, mapping each to its
# in-container /htdocs/wp-content/... path.
#
# This is intentionally a HOST-side script, not baked into the image/
# entrypoint: VS Code reads launch.json from the host repo, and the mappings
# depend on which plugins/themes/mu-plugins are bind-mounted for a given
# stack — information that only exists once the dev/test mount generator
# (a later migration phase) has run. Not wired into any pnpm command yet.
#
# usage: ./generate-vscode-launch.sh
#

set -eo pipefail

readonly GIT_ROOT_PATH="$(git rev-parse --show-toplevel)"
cd "$GIT_ROOT_PATH"

function plugins {
  for PLUGIN in $(find packages/wp-plugin -mindepth 1 -maxdepth 1 -type d -printf '%f\n' 2>/dev/null || echo ''); do
    echo "        \"/htdocs/wp-content/plugins/${PLUGIN}\":\"\${workspaceFolder}/packages/wp-plugin/${PLUGIN}\","
  done
}

function mu_plugins {
  for PLUGIN in $(find packages/wp-mu-plugin -mindepth 1 -maxdepth 1 -type d -printf '%f\n' 2>/dev/null || echo ''); do
    echo "        \"/htdocs/wp-content/mu-plugins/${PLUGIN}.php\":\"\${workspaceFolder}/packages/wp-mu-plugin/${PLUGIN}/${PLUGIN}.php\","
    echo "        \"/htdocs/wp-content/mu-plugins/${PLUGIN}\":\"\${workspaceFolder}/packages/wp-mu-plugin/${PLUGIN}/${PLUGIN}\","
  done
}

function themes {
  for THEME in $(find packages/wp-theme -mindepth 1 -maxdepth 1 -type d -printf '%f\n' 2>/dev/null || echo ''); do
    echo "        \"/htdocs/wp-content/themes/${THEME}\":\"\${workspaceFolder}/packages/wp-theme/${THEME}\","
  done
}

mkdir -p .vscode
cat <<EOF > .vscode/launch.json
{
  // THIS FILE IS MACHINE GENERATED by packages/docker/wp-alpine/scripts/generate-vscode-launch.sh - DO NOT EDIT!
  // If you need to configure additional launch configurations consider defining them in a vscode *.code-workspace file
  "version": "0.2.0",
  "configurations": [
    {
      "name": "wp-alpine",
      "type": "php",
      "request": "launch",
      "port": 9003,
      "stopOnEntry": false,
      "log": false,
      "pathMappings": {
$(plugins)
$(mu_plugins)
$(themes)
        "/htdocs": "\${workspaceFolder}/mnt/wordpress-core"
      }
    }
  ]
}
EOF
